-- !Ups

CREATE TABLE "HABITS"(
  "ID" UUID PRIMARY KEY,
  "NAME" VARCHAR(250) NOT NULL,
  "GOAL"  TEXT,
  "TOTAL_DAYS" INT DEFAULT 0,
  "STREAK" INT DEFAULT 0
);

CREATE TABLE "HABIT_TRACKING"(
  "TRACKING_ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "HABIT_ID" UUID REFERENCES "HABITS"("ID") ON DELETE CASCADE,
  "DATE" DATE NOT NULL DEFAULT CURRENT_DATE,
  "COMPLETED" BOOLEAN DEFAULT FALSE
);

-- !Downs

DROP TABLE IF EXISTS "HABITS";
DROP TABLE IF EXISTS "HABIT_TRACKING";
